{include file="partials/header.tpl"}


<div class="container">
	<div class="row">
		<div class="col-md-12">
			<ol class="breadcrumb">
          		<li><a href="#">Accueil</a></li>
         		<li class="active"><a href="#">Conditions générales d'utilisation</a></li>
          		<!--li class="active">Data</li-->
         	 </ol>

				<h1> Conditions générales d'utilisation</h1>
				<p> 1. OBJET <br> 
Les présentes conditions générales ont pour objet de définir les conditions dans lesquelles Vous pouvez bénéficier des services standards (ci-après dénommés les Services Standards) accessibles sur le site www.wf3network.com (ci-après dénommé le Site). \Vous\ signifie tout utilisateur de l'un quelconque des Services Standards (ci-après dénommé les Services). <br> 
Au cours de Votre utilisation du Site, Vous pouvez être soumis à des conditions d'utilisation particulières à certains Services, lesquelles complètent les présentes conditions générales et en cas de contradiction, prévalent sur ces dernières. <br> <br> 
2. EXPLOITANT DU SITE ET DES SERVICES  <br> 
Le Site et les Services sont exploités par la société WEB FORCE 3 (ci-après dénommée WEB FORCE 3), immatriculée au RCS de Paris sous le n° XXX XXX XXX, dont le siège social est situé 224 rue du Faubourg Saint Antoine 75012 Paris. <br> <br> 
3. ADHESION AUX PRESENTES CONDITIONS GENERALES <br> 
En acceptant d'utiliser les Services, Vous acceptez d'être engagés par les présentes conditions générales, sans restriction ni réserve et reconnaissez en avoir pris connaissance dans leur intégralité. Toute adhésion sous réserve est considérée comme nulle et non avenue. Si Vous n'êtes pas d'accord avec ces conditions générales, qui ne sont pas modifiables par Vous, Vous ne devez pas accéder au Site ni utiliser les Services. <br> <br> 
4. INSCRIPTION AUX SERVICES <br>
4.1. INSCRIPTION AUX SERVICES STANDARDS <br> 
Pour pouvoir accéder aux Services Standards du Site, Vous pouvez être tenu de :
(I)remplir une fiche d'inscription, en y complétant toutes les informations requises et en Vous engageant à ne fournir que des données vraies, exactes, à jour et sincères. Vous vous engagez également à prévenir spontanément WEB FORCE 3 d'un quelconque changement dans lesdites informations à l'adresse de contact indiquée à l'article 12 des présentes conditions générales afin que ces données répondent toujours aux critères susvisés. Si l'une ou plusieurs de ces informations s'avèrent fausses, erronées, inexactes, périmées ou incomplètes, WEB FORCE 3 se réserve le droit de suspendre ou fermer Votre compte, à tout moment et sans préavis ;
(II) Vous connecter sur le site grâce à l’identifiant et le mot de passe émis sur votre boîte mail, et choisir un nouveau mot de passe que une fois connecté sur le Site. Ce mot de passe pourra être modifier seul et à tout moment. Il est recommandé de le faire régulièrement. L'inscription aux Services permet de Vous voir attribuer un espace personnel sous une forme et selon les moyens techniques que WEB FORCE 3 juge les plus appropriés pour rendre les Services. Cet espace personnel Vous permet notamment de :
- créer votre curriculum vitae (ci-après dénommé CV) et de le mettre en ligne comme défini à l'article 7.1.1 des présentes conditions générales, <br> 
- restreindre l'accès des tiers à Vos Pages Personnelles comme indiqué à l'article 7.1.1.c., <br> 
- intégrer à Vos Pages Personnelles un Blog dont les conditions sont définies à l'article 7.1.2 des présentes conditions générales. <br> <br>  

5. USAGE STRICTEMENT PERSONNEL <br>
Est considéré comme étant l'utilisateur des Services la personne dont les renseignements personnels correspondent à ceux qui ont été fournis sur la fiche d'inscription, à l'exclusion de tous autres tiers. Vous vous engagez par conséquent à utiliser personnellement les Services et à ne permettre à aucun tiers de les utiliser à Votre place ou pour Votre compte, sauf à en supporter l'entière responsabilité. Vous êtes pareillement responsable du maintien de la confidentialité de Vos identifiants et mots de passe. En cas de manquement à l'une quelconque des dispositions du présent paragraphe, WEB FORCE 3 se réserve le droit de suspendre ou fermer Votre compte à tout moment et sans préavis. Vous devrez immédiatement contacter WEB FORCE 3 à l'adresse mentionnée à l'article 14 des présentes conditions générales d'utilisation, si Vous remarquez que Votre compte a été utilisé à Votre insu. Vous reconnaissez à DOYOUBUZZ le droit de prendre toutes mesures appropriées en pareil cas. <br> <br> 
6. DESCRIPTION DES SERVICES <br>
DOYOUBUZZ Vous fournit les Services ci-dessous décrits aux conditions suivantes : <br> <br> 
6.1. SERVICES STANDARDS <br> 
6.1.1. EDITION DE CURRICULUM VITAE <br> 
6.1.1.a. OBJET DU SERVICE <br>
WEB FORCE 3 Vous offre la faculté, dans les conditions et limites prévues aux présentes, de créer Votre curriculum vitae (ci-après dénommé CV) et de le mettre en ligne, sous une forme et selon les moyens techniques que WEB FORCE 3 juge les plus appropriés pour rendre ledit Service. A cette fin, il Vous est proposé un modèle de CV standard, constitué d'une page d'accueil et de plusieurs pages secondaires dont le nombre est laissé à la libre appréciation de WEB FORCE 3 (ci-après toutes dénommées les Pages Personnelles), ces pages étant organisées sous forme de rubriques. Ces rubriques sont les suivantes : expérience, compétence, formation, portfolio et contact. Elles pourront être modifiées à la libre convenance de WEB FORCE 3. <br> <br> 
6.1.1.b. LOCALISATION DE VOS PAGES PERSONNELLES <br> 
Vos Pages Personnelles sont accessibles sur le Site à Vos nom et prénom sous la forme d'un annuaire alphabétique, à un emplacement laissé au libre choix de WEB FORCE 3. Vos Pages Personnelles peuvent également être retrouvées à l'aide d'un moteur de recherche. Elles seront directement accessibles partiellment ou entièrement à partir de l'adresse url http://www.wf3network.com/prenom-nom/. Dans le cas d'homonymie, une adresse alternative Vous sera automatiquement proposée. <br> <br> 
6.1.1.c. VOS OBLIGATIONS ET GARANTIES EN MATIERE D’EDITION DE CV <br> 
VOUS ETES LE REDACTEUR ET L'EDITEUR DES CONTENUS SUR VOS PAGES PERSONNELLES (CI-APRES DENOMMEES LES CONTENUS). VOUS EN ETES DONC LE SEUL RESPONSABLE, WEB FORCE 3 N'ASSURANT AUCUNE MODERATION OU CONTROLE PREALABLE D'AUCUNE SORTE. EN QUALITE D'AUTEUR ET D'EDITEUR DES CONTENUS INCLUS DANS VOS PAGES PERSONNELLES, VOUS DECLAREZ ET GARANTISSEZ EXPRESSEMENT A WEB FORCE 3 : - QUE LES INFORMATIONS VOUS CONCERNANT AU SEIN DE VOTRE CV SONT EN RELATION AVEC VOTRE IDENTITE PROFESSIONNELLE ; - QU'ELLES SONT VRAIES, EXACTES, A JOUR ET SINCERES ; - QUE VOUS ETES LE SEUL ET UNIQUE PROPRIETAIRE DE L'INTEGRALITE DES DROITS DE PROPRIETE INTELLECTUELLE RELATIFS A CES CONTENUS ET DANS LE CAS CONTRAIRE, QUE VOUS AVEZ ACQUIS TOUTES LES AUTORISATIONS, LICENCES, CONCESSIONS NECESSAIRES A LEUR DIFFUSION DE LA PART DE TOUS AUTEURS ET PLUS GENERALEMENT, DE TOUS TITULAIRES DE DROITS SUR TOUT OU PARTIE DES CONTENUS ; - QUE VOUS AVEZ OBTENU TOUTES LES AUTORISATIONS NECESSAIRES DE LA PART DE TOUTES PERSONNES DONT L'IMAGE EST REPRODUITE DANS LESDITS CONTENUS, OU DE TOUTES PERSONNES TITULAIRES DE L'AUTORITE POUR Y CONSENTIR ; - QUE VOUS AVEZ OBTENU TOUTES LES AUTORISATIONS NECESSAIRES DE LA PART DE TOUTES PERSONNES DONT LES BIENS SONT REPRODUITS DANS LESDITS CONTENUS ; - QUE VOUS N'ENFREIGNEZ D'UNE MANIERE GENERALE AUCUN DROIT APPARTENANT A UN TIERS, QUELLE QU'EN SOIT LA NATURE OU LA CAUSE, DU FAIT DESDITS CONTENUS. <br> <br> 
VOUS DECLAREZ ET GARANTISSEZ EXPRESSEMENT A WEB FORCE 3 QUE VOS CONTENUS VOUS SONT EXCLUSIVEMENT PERSONNELS, QU'ILS SONT LICITES, SONT CONFORMES A L'OBJET DU SERVICE, A SAVOIR LA PROMOTION DE VOTRE IDENTITE PROFESSIONNELLE SUR INTERNET, NE PORTENT ATTEINTE NI A L'ORDRE PUBLIC, NI AUX BONNES MŒURS ET QUE D'UNE MANIERE GENERALE, ILS N'ENFREIGNENT AUCUNE DISPOSITION LEGALE OU REGLEMENTAIRE, NOTAMMENT D'ORDRE PENAL. A DEFAUT POUR VOUS DE RESPECTER L'UNE OU L'AUTRE DES DISPOSITIONS VISEES AU PRESENT ARTICLE, DOYOUBUZZ AURA LE DROIT DE SUSPENDRE OU FERMER VOTRE COMPTE, AINSI QUE DE SUPPRIMER VOS CONTENUS, A TOUT MOMENT ET SANS PREAVIS, COMME DE PRENDRE TOUTES MESURES APPROPRIEES EN SA QUALITE D'HEBERGEUR DES CONTENUS, SUR SIMPLE RECLAMATION DES TIERS. <br> <br> 
7. USAGE NON COMMERCIAL <br> 
Vous vous interdisez de monnayer, vendre et concéder tout ou partie de l'accès aux Services, aux serveurs du Site, ainsi qu'aux informations qui y sont hébergées et/ou partagées. En cas de manquement à cette règle, WEB FORCE 3 se réserve le droit de suspendre ou fermer Votre compte, à tout moment et sans préavis, ainsi que d'engager toutes actions judiciaires.
8. FIN DES SERVICES <br> 
8.1. DESINSCRIPTION AUX SERVICES <br> 
Vous pouvez vous désinscrire aux Services quand Vous le souhaitez. Pour cela, il suffit de Vous rendre sur les informations de Votre compte et de suivre le lien \supprimer mon compte\. Cette désinscription aura pour effet de supprimer l'ensemble des informations contenues dans Votre CV, ainsi que dans Votre Portfolio et Votre Blog, ce dont Vous déclarez être parfaitement informé et ce que Vous acceptez expressément. <br> <br> 
9. PROPRIETE INTELLECTUELLE <br>
Les systèmes, logiciels, structures, infrastructures, bases de données et contenus (textes, images, visuels, musiques, logos, marques, etc …) exploités par WEB FORCE 3 au sein du Site sont protégés par tous droits de propriété intellectuelle. Tous désassemblages, décompilations, décryptages, extractions, réutilisations, copies et plus généralement, tous actes de reproduction, représentation, diffusion et utilisation de l'un quelconque de ses éléments, en tout ou partie, sans l'autorisation de WEB FORCE 3, sont strictement interdits et feront l'objet de poursuites judiciaires. La seule exception autorisée par la loi est la copie privée, c'est-à-dire la copie par Vous-même de ces éléments pour Votre seul et unique usage personnel et à des fins non commerciales. <br> <br> 
10. COMPORTEMENTS PROHIBES <br> 
Sont strictement interdits, à peine de poursuites judiciaires (i) tous comportements de nature à interrompre, suspendre, ralentir ou empêcher la continuité des Services, (ii) toutes intrusions ou tentatives d'intrusions dans les systèmes de WEB FORCE 3, (iii) tous détournements des ressources système du Site, (iv) toutes actions de nature à imposer une charge disproportionnée sur les infrastructures de ce dernier, (v) toutes atteintes aux mesures de sécurité et d'authentification et (vi) tous actes de nature à porter atteinte aux droits et intérêts financiers, commerciaux ou moraux de WEB FORCE 3 ou des utilisateurs de son Site. En cas de manquement à l'une quelconque des dispositions du présent paragraphe ou plus généralement, d'infractions aux lois et règlements, WEB FORCE 3 se réserve le droit de suspendre ou fermer Votre compte à tout moment et sans préavis, ainsi que d'engager toutes actions en justice. <br> 
11. SITES TIERS <br> <br> 
Vous reconnaissez et acceptez que WEB FORCE 3 ne puisse être tenu en aucun cas pour responsable de la disponibilité technique de sites internet exploités par des tiers auxquels Vous accéderiez par l'intermédiaire du Site. WEB FORCE 3 n'endosse aucune responsabilité au titre des contenus, publicités, produits et/ou services disponibles sur de tels sites tiers. WEB FORCE 3 n'est pas non plus responsable des transactions intervenues entre Vous et un quelconque annonceur, professionnel ou commerçant vers lequel Vous seriez orienté par l'intermédiaire du Site et ne saurait en aucun cas être partie à quelques litiges éventuels que ce soit avec ces tiers concernant notamment la livraison de produits et/ou services, les garanties, déclarations et autres obligations quelconques auxquelles ces derniers sont tenus. <br> <br> 
12. CONTACT <br> 
Si Vous souhaitez nous faire part de Vos commentaires, nous communiquer une information ou nous poser une question concernant l'utilisation du Site et des Services, à l'exception des plaintes prévues à l'article 17 ci-dessous, Vous pouvez nous contacter à l'adresse électronique suivante : xxxxxx@xxxxxx.com. <br> <br> 
13. EXCLUSION DE GARANTIE ET DE RESPONSABILITE DE DOYOUBUZZ DANS LE CADRE DES SERVICES STANDARDS <br> 
LES SERVICES STANDARDS VOUS SONT FOURNIS TELS QUELS ET SANS AUCUNE GARANTIE D'AUCUNE SORTE, EXPRESSE OU IMPLICITE. DOYOUBUZZ NE VOUS GARANTIT NOTAMMENT PAS : - QUE LES SERVICES STANDARDS, SOUMIS A UNE RECHERCHE CONSTANTE POUR EN AMELIORER NOTAMMENT LA PERFORMANCE ET LE PROGRES, SERONT TOTALEMENT EXEMPTS D'ERREURS, DE VICES OU DEFAUTS ; - QUE LES SERVICES ETANT STANDARD ET NULLEMENT PROPOSES A VOTRE SEULE INTENTION EN FONCTION DE VOS PROPRES CONTRAINTES PERSONNELLES, REPONDRONT SPECIFIQUEMENT A VOS BESOINS ET ATTENTES ; - QUE LE SITE FONCTIONNERA DE MANIERE ININTERROMPUE, WEB FORCE 3 SE RESERVANT LA FACULTE D'INTERROMPRE MOMENTANEMENT L'ACCES AU SITE POUR DES RAISONS DE MAINTENANCE ET NE POUVANT EN AUCUN CAS ETRE TENU POUR RESPONSABLE DES PERTURBATIONS OU DEFAILLANCES DU RESEAU INTERNET.
WEB FORCE 3 NE SAURA EN AUCUN CAS ETRE REDEVABLE ENVERS VOUS DU PAIEMENT DE QUELCONQUES DOMMAGES ET INTERETS, DE QUELQUE NATURE QU'ILS SOIENT, DIRECTS OU INDIRECTS, MATERIELS, FINANCIERS OU MORAUX EN RAISON DE L'UTILISATION QUE VOUS FAITES DES SERVICES STANDARDS ET DU SITE. DOYOUBUZZ QUI N'EST PAS UNE AGENCE D'INTERIM, NI VOTRE MANDATAIRE, N'EST NOTAMMENT PAS RESPONSABLE DES RELATIONS ET ENTRETIENS QUE VOUS POUVEZ AVOIR AVEC DES RECRUTEURS POTENTIELS AVEC QUI VOUS ENTREZ EN CONTACT PAR VOS PROPRES MOYENS, DE VOTRE PROPRE CHEF ET SOUS VOTRE SEULE ET ENTIERE RESPONSABILITE. VOUS DECLAREZ ETRE PARFAITEMENT INFORME DE CE QUE LE SITE PERMET A TOUTES PERSONNES D'EDITER DES CONTENUS ET OFFRE EGALEMENT DES SERVICES DE BLOGS, CHATS ET FORUMS. DOYOUBUZZ NE PEUT ETRE TENU POUR RESPONSABLE, EN SA QUALITE DE SIMPLE HEBERGEUR, DES CONTENUS DONT LES AUTEURS SONT DES TIERS. VOUS VOUS INTERDISEZ AINSI DE RECHERCHER LA RESPONSABILITE DE DOYOUBUZZ DU FAIT DE CES CONTENUS ET VOUS VOUS ENGAGEZ A DIRIGER TOUTE RECLAMATION EVENTUELLE, SI DES CONTENUS HERBERGES SUR LE SITE DEVAIENT VOUS CAUSER UN PREJUDICE, DIRECTEMENT VERS L'AUTEUR DES CONTENUS EN QUESTION. DOYOUBUZZ MET TOUTEFOIS A VOTRE DISPOSITION UN FORMULAIRE DE PLAINTE DANS LES CONDITIONS DEFINIES A L'ARTICLE 17 CI-DESSOUS. CETTE PROCEDURE DE NOTIFICATION NE SAURAIT TOUTEFOIS ETRE CONSIDEREE COMME UNE RECONNAISSANCE DE LA PART DE DOYOUBUZZ D'UNE QUELCONQUE OBLIGATION A INTERVENIR MAIS UNIQUEMENT COMME LE RESPECT PAR WEB FORCE 3 DE L'ARTICLE 6-III DE LA LOI N° 2004-575 DU 21 JUIN 2004 EN SA QUALITE DE SIMPLE HEBERGEUR. <br> <br> 
14. PLAINTES <br>
Tous actes commis sur le Site qui Vous seraient préjudiciable peuvent faire l’objet d’une plainte auprès de WEB FORCE 3. Cette plainte doit automatiquement être transmise à l’adresse suivante : WEB FORCE 3, 224 rue du Faubourg Saint Antoine 75012 Paris Ou à l’adresse électronique suivante : xxxxxx@xxxxxx.com La plainte doit comporter obligatoirement la date de sa notification, l’identité du plaignant (s’il s’agit d’une personne physique : ses nom, prénom, profession, domicile, nationalité, date et lieu de naissance ; s’il s’agit d’une personne morale : sa forme, sa dénomination, son siège social et l’organe qui la représente légalement), les noms et domicile du destinataire (s’il s’agit d’une personne morale, sa dénomination et son siège social), la description des faits litigieux et leur localisation précise, les motifs pour lesquels le contenu doit être retiré, comprenant la mention des dispositions légales et des justifications de faits, ainsi que la copie de la correspondance adressée à l’auteur ou à l’éditeur des informations ou activités litigieuses demandant leur interruption, leur retrait ou leur modification, ou la justification de ce que l’auteur ou l’éditeur n’a pu être contacté. WEB FORCE 3 aura la libre faculté de prendre toutes mesures appropriées, sans aucun engagement de sa part et/ou de transmettre cette plainte aux autorités compétentes. <br> <br> 
15. DONNEES PERSONNELLES <br> 
Vous reconnaissez et acceptez que la gestion des Services implique le traitement informatique de données qui Vous sont personnelles. WEB FORCE 3 s'engage à protéger ces données, celles-ci étant traitées avec la plus stricte confidentialité et la plus grande prudence. Les données personnelles collectées seront utilisées aux fins et selon les conditions décrites dans la Charte relative à la protection des données à caractère personnel. Conformément aux articles 39 et suivants de la loi n° 78-17 du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés, Vous êtes informé du droit qui Vous est reconnu d'obtenir la communication et, le cas échéant, la rectification ou la suppression des informations Vous concernant, en adressant Votre demande à l'adresse électronique suivante : xxxxxx@xxxxxx.com ou par courrier, à l'adresse suivante : WEB FORCE 3, 224 rue du Faubourg Saint Antoine 75012 Paris. <br> <br> 
16. LOI APPLICABLE ET JURIDICTION COMPETENTE <br>
Les présentes conditions générales sont régies par la loi française. En cas de contestation sur leur interprétation et/ou leur exécution, les parties conviennent que les tribunaux de Paris seront exclusivement compétents pour en juger, sauf règles de procédure impératives contraires. <br> <br> 

17. MODIFICATION DES SERVICES <br> 
WEB FORCE 3 se réserve le droit, à sa seule discrétion, de modifier à tout moment les Services Standards et les dispositions des présentes conditions générales d'utilisation qui y sont relatives, en totalité ou en partie. WEB FORCE 3 se réserve également le droit de supprimer purement et simplement certains Services Standards. Vous ne pourrez former aucune réclamation à ce titre.
Vous serez informé par courrier électronique ou tout autre moyen de la modification des Services Standards et/ou des présentes conditions générales d’utilisation et invité à consulter les termes des nouvelles conditions d’utilisation.
Si Vous n’agréez pas les modifications intervenues, Vous devez nous manifester Votre refus par courrier électronique à l’adresse électronique suivante : xxxxxx@xxxxxx.com et Vous interdire en conséquence d’accéder au Site et/ou d’utiliser les Services Standards dans la mesure où cet usage serait concerné par les modifications non agréées. Le cas échéant, WEB FORCE 3 se réserve le droit de suspendre ou supprimer Votre compte. <br> 
A défaut de refus exprès de Votre part ou si, malgré Votre refus, Vous continuez à utiliser le ou les Services Standards concernés par les modifications, Vous serez réputé avoir accepté les modifications intervenues qui Vous seront alors pleinement opposables. <br> <br> 

18. ENTREE EN VIGUEUR <br> 
Les présentes conditions générales sont entrées en vigueur le 31/07/2015.

</p>
			
		</div><!--fin col-md-12-->
	</div><!-- fin row-->
</div> <!-- fin container-->


{include file="partials/footer.tpl"}