-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 11:18:16 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wf3network
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wf3network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wf3network` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wf3network` ;

-- -----------------------------------------------------
-- Table `wf3network`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `photo` VARCHAR(100) NULL COMMENT '',
  `name` VARCHAR(50) NULL COMMENT '',
  `firstname` VARCHAR(50) NULL COMMENT '',
  `date_promo` DATETIME NULL COMMENT '',
  `age` INT NULL COMMENT '',
  `mail` VARCHAR(100) NULL COMMENT '',
  `telephone` VARCHAR(50) NULL COMMENT '',
  `site` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL COMMENT '',
  `publish` TINYINT(1) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
ROW_FORMAT = Dynamic;


-- -----------------------------------------------------
-- Table `wf3network`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`project` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `description` TEXT(65536) NULL COMMENT '',
  `url` VARCHAR(100) NULL COMMENT '',
  `profile_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_projet_profil1_idx` (`profile_id` ASC)  COMMENT '',
  CONSTRAINT `fk_projet_profil1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `wf3network`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wf3network`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`user` (
  `id` INT NOT NULL COMMENT '',
  `type` TINYINT(1) NULL COMMENT '',
  `login` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `profile_id` INT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wf3network`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tag` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wf3network`.`profile_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`profile_tag` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `profile_id` INT NOT NULL COMMENT '',
  `tag_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_profil_tag_profil_idx` (`profile_id` ASC)  COMMENT '',
  INDEX `fk_profil_tag_tags1_idx` (`tag_id` ASC)  COMMENT '',
  CONSTRAINT `fk_profil_tag_profil`
    FOREIGN KEY (`profile_id`)
    REFERENCES `wf3network`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profil_tag_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `wf3network`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wf3network`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wf3network`.`profile_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`profile_skill` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `profile_id` INT NOT NULL COMMENT '',
  `skill_id` INT NOT NULL COMMENT '',
  `skill_level` DECIMAL(11,2) NULL COMMENT '',
  `skill_wf3` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_profil_skill_profil1_idx` (`profile_id` ASC)  COMMENT '',
  CONSTRAINT `fk_profil_skill_profil1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `wf3network`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wf3network`.`project_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wf3network`.`project_picture` (
  `id` INT NOT NULL COMMENT '',
  `project_id` INT NOT NULL COMMENT '',
  `src` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_projet_picture_projet1_idx` (`project_id` ASC)  COMMENT '',
  CONSTRAINT `fk_projet_picture_projet1`
    FOREIGN KEY (`project_id`)
    REFERENCES `wf3network`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
